android x support + upgrades
beworker/featured pull request #13
Opened 2019-01-21 13:20 UTC by MFlisar

I removed the app compat dependencies and replaced them with jetbrain dependencies

Additionally I did following:
* updated sdk version from 24 to 28 and also all app compat dependencies
* updated build tools, gradle, gradle wrapper
* extracted version definitions into own file
* minSdk changed to 14, because support version 28 forces this min sdk now
* removed app compat dependency from featured module (replaced `ArrayMap` with `HashMap`)

2019-01-21 22:02 UTC, sergejsha requested changes
Very nice work! Thanks for submitting! Unit tests should run again (basically the same replace task should be applied on them) and we can merge it.

2019-01-21 22:02 UTC, sergejsha commented on featured-compiler/build.gradle
> +    compileOnly deps.android
I had to replace this line with `testCompileOnly deps.android` to be able to run tests. 

The tests and `FeatureHost` stub class used by tests need some attention too. `android.support.annotation.NonNull` should be replaced with `org.jetbrains.annotations.NotNull`. Could you do it please?

2019-01-21 22:04 UTC, beworker commented
Would you also resolve the conflicts please? Not sure why there are some. I haven't merged any changes to master recently.

2019-01-22 10:57 UTC, MFlisar commented
I forked your project recently (the day I created the last issue), not sure why my fork was some commits behind. Merged everything now and fixed all test cases.

2019-01-22 20:38 UTC, merged